### ISSUE TITLE
Contributing to fluentbit-operator

### ISSUE THREAD

**Issue by alexandre-allard-scality** [kubesphere/fluentbit-operator#23]
Hello,

My team and I are working on a Kubernetes distribution named [MetalK8s](https://github.com/scality/metalk8s) and we're currently working on our log centralization system composed of Fluent Bit and Loki.

Your project seems really interesting for us and instead of developing yet another operator (or forking your repository), we would like to contribute to your project to help you integrate new plugins support such as [Loki Output](https://github.com/grafana/loki/tree/master/cmd/fluent-bit).

First, do you accept contribution?
If yes, do you have guidelines?

Otherwise, we would like to know what motivated your choice for building this operator instead of using already existing things like [Logging Operator](https://github.com/banzaicloud/logging-operator)?
But above all, why basing the log collection only on Fluent Bit rather than the Fluent Bit + Fluentd couple as we can find in most log centralization architecture using Fluent Bit?
On our side, we chose this to have a minimal resources consumption, but is there anything else motivating your choice?
We're still thinking of our implementation choice and it would help us a lot to have your thought.

Thanks,

MetalK8s team.

**Comment by benjaminhuo** [comment]
Hi @alexandre-allard-scality , yes sure we'll definitely accept your contribution. The dev guide is here, https://github.com/kubesphere/fluentbit-operator#contributing , it's a bit simple though. Let us know if you need anything else.

We did considering logging operator for a while, we develop FluentBit operator by ourselves for a few reasons:

- For logging operator, all logs has to flow from FluentBit to Fluentd, and Fluentd might become a single point of failure.

- Actually, we developed Fluentbit forward output crd https://github.com/kubesphere/fluentbit-operator/blob/master/docs/plugins/output/forward.md which can output logs from to Fluentd . So if user want to use Fluentd to forward logs to more sinks, he can use the forward output crd to integrate with Fluentd for now. 

We do have plan to develop crds for Fluentd to deploy Fluentd as a deployment, ideally it will help users to deploy Fluentd with ease into K8s. The Fluentd crds should be an optional choice instead of a mandatory one in a logging stack in our opinion.  

- FluentBit's minimal resource consumption is indeed an important factor that we choose to support it by default.

- Another reason we develop FluentBit operator is that we found that we have to restart FluentBit pod to reload new FluentBit configs, there is no reload interface when we develop FluentBit operator. Pls refer to https://github.com/fluent/fluent-bit/pull/842 and https://github.com/fluent/fluent-bit/issues/365

- And we do have plan to integrate our logging sidecar function into FluentBit operator which helps to collect logs files on Pod's volume instead of stdout

@huanggze is the core maintainer of FluentBit Operator, @huanggze do you have any comments?

Regards,
Benjamin Huo

**Comment by huanggze** [comment]
Thanks for your message.

Our vision is to make a tool for cluster operators to build k8s logging layer flexibly and efficiently. As @benjaminhuo mentioned, we start with lightweight Fluent Bit , but will incorporate Fluentd in the future. 

Here is our broad features or roadmap:
- Automate the deployment of Fluentd and Fluent Bit (as daemonset/deployment)
- Configure and reload Fluentd and Fluent Bit dynamically
- Switch on/off input, filter and output plugins
- Select and group multiple plugins for different logging purposes
- Inject sidecar container to collect log files on pod volume
- Support full Fluent Bit/Fluentd plugins (Loki will definitely be includede.)

**Comment by benjaminhuo** [comment]
@alexandre-allard-scality we developed FluentBit Operator using kubebuilder.
@huanggze which kubebuilder version we use? Maybe we coud put kubebuild related info into contribute guide as well.

**Comment by huanggze** [comment]
The project is build with v2.3.0

**Comment by alexandre-allard-scality** [comment]
Thanks for the quick answers,

Ok, that's cool, we totally agree on the fact that Fluentd must be optional, that's the reason we didn't chose logging-operator. 

As I said, we're currently working on our log centralization system, so we will probably start working on the Loki output plugin integration soon. We will let you know if we have question regarding the good practices or anything else.

**Comment by benjaminhuo** [comment]
> Thanks for the quick answers,
> 
> Ok, that's cool, we totally agree on the fact that Fluentd must be optional, that's the reason we didn't chose logging-operator.
> 
> As I said, we're currently working on our log centralization system, so we will probably start working on the Loki output plugin integration soon. We will let you know if we have question regarding the good practices or anything else.

We're looking forward to your loki output plugin :) 
Let us know if you need any other info

Regards,
Ben

**Comment by benjaminhuo** [comment]
@alexandre-allard-scality , you can join our [slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) channel sig-observability anytime you have questions

**Comment by benjaminhuo** [comment]
Loki plugin has already been added.
Close this issue for now
